//@version=5
strategy("EMA Trend Strategy", overlay=true)

// 定义 EMA 参数
ema1_length = 1
ema7_length = 7

// 计算 EMA 值
ema1 = ta.ema(close, ema1_length)
ema7 = ta.ema(close, ema7_length)

// 定义策略信号
var string signal = na
var float entry_price = na
var float stop_price = na

// 参数设置分组
string strategy_group = "参数设置"

// 参数设置
var qty =input(100, tooltip = "每次投入资金")

// 检查条件并生成信号
if (ta.crossover(ema1, ema7))
    signal := "LONG"
else if (ta.crossunder(ema1, ema7))
    signal := "SHORT"
else
    signal := na
    
// 绘制买入标签并开仓
if (signal == "LONG")
    label.new(bar_index, high, yloc=yloc.abovebar, text="BUY", style=label.style_label_down, color=color.green, textcolor=color.white, size=size.small)
    strategy.order('LONG', direction = strategy.long, qty = 100 / close)
    entry_price := close
    stop_price := low

if (signal == "SHORT")
    label.new(bar_index, low, yloc=yloc.belowbar, text="BUY", style=label.style_label_down, color=color.red, textcolor=color.white, size=size.small)
    strategy.order('SHORT', direction = strategy.short, qty = 100 / close)
    entry_price := close
    stop_price := high

// 检查平仓条件并绘制卖出标签和平仓
if (strategy.position_size > 0)
    if (low < low[1])
        strategy.close("LONG")
        label.new(bar_index, high, yloc=yloc.abovebar, text="SELL LONG", style=label.style_label_down, color=color.red, textcolor=color.white, size=size.small)

if (strategy.position_size < 0)
    if (low > low[1])
        strategy.close("SHORT")
        label.new(bar_index, low, yloc=yloc.belowbar, text="SELL SHORT", style=label.style_label_up, color=color.green, textcolor=color.white, size=size.small)

// 输出 EMA 值以便于调试和验证
plot(ema1, color=#e221f3, title="EMA 1")
plot(ema7, color=color.orange, title="EMA 7")
